---

- name: Update netbox configuration directory
  file:
    path: "{{ netbox_root_dir }}/configuration"
    state: directory
    recurse: true

- name: Update configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ netbox_root_dir }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - netbox.env
    - configuration/configuration.py
    - configuration/gunicorn_config.py
  notify: restart netbox
