---

- name: update netbox directories
  file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - configuration
    - env

- name: update environment files
  template:
    src: "env/{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/env/{{ item }}"
  loop:
    - netbox.env
    - postgres.env
    - redis-cache.env
    - redis.env
  notify: restart netbox

- name: copy configuration file
  ansible.builtin.copy:
    src: files/configuration.py
    dest: "{{ netbox_base_dir }}/configuration/"
    owner: root
    group: root
    mode: '0644'

- name: update configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/{{ item }}"
  loop:
    - docker-compose.yml
    - docker-compose.override.yml
  notify: restart netbox

- name: remove outdated files
  file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: absent
  loop:
    - netbox.env
    - configuration/gunicorn_config.py
